//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "channels")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text", nullable)]
    pub channel_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub owner_id: Option<String>,
    pub tax_rate: Option<i32>,
    pub in_stock_market: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::products::Entity")]
    Products,
    #[sea_orm(has_one = "super::stocks::Entity")]
    Stocks,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::OwnerId",
        to = "super::users::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Products.def()
    }
}

impl Related<super::stocks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Stocks.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::products::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::products::Relation::Channels.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
