//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "stocks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text", nullable)]
    pub channel_id: Option<String>,
    pub value: Option<Decimal>,
    #[sea_orm(column_type = "Text", nullable)]
    pub history: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_updated: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::channels::Entity",
        from = "Column::ChannelId",
        to = "super::channels::Column::ChannelId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Channels,
    #[sea_orm(has_many = "super::stock_shares::Entity")]
    StockShares,
}

impl Related<super::channels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Channels.def()
    }
}

impl Related<super::stock_shares::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StockShares.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
