//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text", nullable)]
    pub user_id: Option<String>,
    pub tokens: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_daily: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_job: Option<String>,
    pub debt: Option<i32>,
    pub in_stock_market: Option<i32>,
    pub xp: Option<i32>,
    pub level: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_message_time: Option<String>,
    pub love_xp: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_channel_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::channels::Entity")]
    Channels,
    #[sea_orm(has_one = "super::global_message_counts::Entity")]
    GlobalMessageCounts,
    #[sea_orm(has_many = "super::inventory::Entity")]
    Inventory,
    #[sea_orm(has_many = "super::products::Entity")]
    Products,
    #[sea_orm(has_many = "super::rings::Entity")]
    Rings,
    #[sea_orm(has_many = "super::stock_shares::Entity")]
    StockShares,
}

impl Related<super::global_message_counts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GlobalMessageCounts.def()
    }
}

impl Related<super::inventory::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Inventory.def()
    }
}

impl Related<super::products::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Products.def()
    }
}

impl Related<super::rings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Rings.def()
    }
}

impl Related<super::stock_shares::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StockShares.def()
    }
}

impl Related<super::channels::Entity> for Entity {
    fn to() -> RelationDef {
        super::products::Relation::Channels.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::products::Relation::Users.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
