name: rust analyze

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '35 6 * * 3'

jobs:
  rust-clippy-analyze:
    name: Run rust-clippy analyzing
    runs-on: rust
    steps:
      - name: Checkout code
        run: |
          rm -rf ./* .git || true

          # Clone safely, using the Forgejo token in case the repo is private
          git -c http.extraheader="AUTHORIZATION: bearer ${{ forgejo.token }}" \
            clone --depth 1 --branch ${{ forgejo.ref_name }} \
            ${{ forgejo.server_url }}/${{ forgejo.repository }}.git .

      - name: Install clippy
        run: rustup component add clippy

      - name: Run rust-clippy
        run: cargo clippy --all-features -- -D warnings

      - name: Run and Build
        run: cargo build --release
