jobs:
  rust-clippy-analyze:
    name: Run rust-clippy analyzing
    runs-on: rust
    steps:
      - name: Checkout code
        run: |
          git clone --depth 1 --branch ${{ forgejo.ref_name }} ${{ forgejo.server_url }}/${{ forgejo.repository }} .

      - name: Install clippy component
        run: rustup component add clippy

      - name: Run rust-clippy
        run: cargo clippy --all-features --message-format=json
        continue-on-error: false
