//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "items")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub description: String,
    pub item_type: String,
    pub quantity: i64,
    pub price: i64,
    pub origin_cid: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::channels::Entity",
        from = "Column::OriginCid",
        to = "super::channels::Column::Cid",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Channels,
    #[sea_orm(has_many = "super::inventory::Entity")]
    Inventory,
}

impl Related<super::channels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Channels.def()
    }
}

impl Related<super::inventory::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Inventory.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::inventory::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::inventory::Relation::Items.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
