//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod channels;
pub mod global_message_counts;
pub mod guild_settings;
pub mod inventory;
pub mod marriages;
pub mod products;
pub mod proposals;
pub mod rings;
pub mod stock_shares;
pub mod stocks;
pub mod system_settings;
pub mod users;
