//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "stock_shares")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub channel_id: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text", nullable)]
    pub user_id: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub shares: Option<f64>,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Double", nullable)]
    pub purchase_price: Option<f64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::stocks::Entity",
        from = "Column::ChannelId",
        to = "super::stocks::Column::ChannelId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Stocks,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::UserId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::stocks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Stocks.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
