//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: u64,
    pub tokens: i64,
    pub debt: i64,
    pub last_daily: Option<i64>,
    pub last_job: Option<i64>,
    pub xp: i64,
    pub level: i64,
    pub spouse: Option<i64>,
    pub spouse_since: Option<i64>,
    pub joint_balance: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::channels::Entity")]
    Channels,
    #[sea_orm(has_many = "super::inventory::Entity")]
    Inventory,
}

impl Related<super::channels::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Channels.def()
    }
}

impl Related<super::inventory::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Inventory.def()
    }
}

impl Related<super::items::Entity> for Entity {
    fn to() -> RelationDef {
        super::inventory::Relation::Items.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::inventory::Relation::Users.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
